IF DB_ID ('QL_GIAOHANG') IS NOT NULL
DROP DATABASE QL_GIAOHANG;

GO CREATE DATABASE QL_GIAOHANG;

GO USE QL_GIAOHANG;

GO
CREATE TABLE
    NHACUNGCAP (
        MaNCC CHAR(10) NOT NULL PRIMARY KEY,
        TenNCC NVARCHAR (100) NOT NULL,
        DiaChi NVARCHAR (200),
        DienThoai VARCHAR(15) UNIQUE,
        Email VARCHAR(50) UNIQUE
    );

GO
CREATE TABLE
    LOAIHANG (
        MaLoaiHang CHAR(10) NOT NULL PRIMARY KEY,
        TenLoaiHang NVARCHAR (100) NOT NULL
    );

GO
CREATE TABLE
    MATHANG (
        MaMH CHAR(10) NOT NULL PRIMARY KEY,
        TenMH NVARCHAR (100) NOT NULL,
        DonViTinh NVARCHAR (20) NOT NULL,
        DonGia DECIMAL(18, 2) CHECK (DonGia >= 0),
        SoLuong INT CHECK (SoLuong >= 0),
        MaNCC CHAR(10),
        MaLoaiHang CHAR(10),
        CONSTRAINT FK_MH_NCC FOREIGN KEY (MaNCC) REFERENCES NHACUNGCAP (MaNCC) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT FK_MH_LH FOREIGN KEY (MaLoaiHang) REFERENCES LOAIHANG (MaLoaiHang) ON DELETE CASCADE ON UPDATE CASCADE
    );

GO -
CREATE TABLE
    NHANVIEN (
        MaNV CHAR(10) NOT NULL PRIMARY KEY,
        HoTen NVARCHAR (100) NOT NULL,
        GioiTinh NVARCHAR (3) CHECK (GioiTinh IN (N'Nam', N'Nữ')),
        NgaySinh DATE CHECK (NgaySinh < GETDATE ()),
        DiaChi NVARCHAR (200),
        DienThoai VARCHAR(15) UNIQUE,
        CONSTRAINT CK_NV_TuoiLamViec CHECK (
            DATEDIFF (YEAR, NgaySinh, GETDATE ()) >= 18
            AND DATEDIFF (YEAR, NgaySinh, GETDATE ()) <= 60
        )
    );

GO
CREATE TABLE
    KHACHHANG (
        MaKH CHAR(10) NOT NULL PRIMARY KEY,
        TenKH NVARCHAR (100) NOT NULL,
        DiaChi NVARCHAR (200),
        DienThoai VARCHAR(15) UNIQUE,
        Email VARCHAR(50) UNIQUE
    );

GO
CREATE TABLE
    DONDATHANG (
        SoDH CHAR(10) NOT NULL PRIMARY KEY,
        NgayDat DATE NOT NULL,
        MaKH CHAR(10),
        MaNV CHAR(10),
        NgayGiao DATE,
        NoiGiao NVARCHAR (200),
        CONSTRAINT CK_NgayGiao CHECK (NgayGiao >= NgayDat),
        CONSTRAINT FK_DH_KH FOREIGN KEY (MaKH) REFERENCES KHACHHANG (MaKH) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT FK_DH_NV FOREIGN KEY (MaNV) REFERENCES NHANVIEN (MaNV) ON DELETE CASCADE ON UPDATE CASCADE
    );

GO
CREATE TABLE
    CHITIETDATHANG (
        SoDH CHAR(10) NOT NULL,
        MaMH CHAR(10) NOT NULL,
        SoLuong INT NOT NULL DEFAULT 1 CHECK (SoLuong > 0),
        DonGia DECIMAL(18, 2) CHECK (DonGia >= 0),
        GiamGia DECIMAL(5, 2) DEFAULT 0 CHECK (
            GiamGia >= 0
            AND GiamGia <= 100
        ),
        CONSTRAINT PK_CTDH PRIMARY KEY (SoDH, MaMH),
        CONSTRAINT FK_CTDH_DH FOREIGN KEY (SoDH) REFERENCES DONDATHANG (SoDH) ON DELETE CASCADE ON UPDATE CASCADE,
        CONSTRAINT FK_CTDH_MH FOREIGN KEY (MaMH) REFERENCES MATHANG (MaMH) ON DELETE CASCADE ON UPDATE CASCADE
    )